News component - v1
cesko-digital/audiozpravy pull request #19
Opened 2021-06-21 16:51 UTC by Terra42

2021-06-21 20:11 UTC, jirizikes requested changes
@Terra42 Ahoj, prošel jsem to. Kód je ok, rozdělila si to skvěle. Graficky je to taky v pořádku.

- Vypadá to že máš nastavenou fixně šířku a výšku, takže se mi to rozpadá na různých rozlišení:

<img width="818" alt="Screenshot 2021-06-21 at 22 03 29" src="https://user-images.githubusercontent.com/47362491/122821407-18c37480-d2dd-11eb-8ad2-3b6046c2f027.png">

- Aktuální záložka by měla být zvýrazěná viz. Figma.

<img width="267" alt="Screenshot 2021-06-21 at 22 07 57" src="https://user-images.githubusercontent.com/47362491/122821468-2da00800-d2dd-11eb-9523-6de149c2a7d4.png">

- Sice komponenta zatím ještě neobsahuje logiku (jiné issue), tak by ale mělo být vše už kliakací. Tzn. místo textu už nějaké buttony, linky apod..

- Jednotlivé kategorie bych udělal scrollovací do stran, např. třeba použít tuto knihovnu: https://github.com/satya164/react-native-tab-view

Jinak to vypadá suprově!

2021-06-25 19:31 UTC, Terra42 commented
Díky za feeback.
1. Předělala jsem rozměry na procenta, takže je to trochu flexibilnější ale i tahle verze se rozpadne na širším displeji. Měl by být design vhodný i pro tablety? 
2. Přidala jsem klikací komponenty a zvýraznění záložky.
3. Na scrollování do strany se podívám zítra :)

2021-06-25 19:47 UTC, jirizikes commented
> Díky za feeback.
> 
> 1. Předělala jsem rozměry na procenta, takže je to trochu flexibilnější ale i tahle verze se rozpadne na širším displeji. Měl by být design vhodný i pro tablety?
> 2. Přidala jsem klikací komponenty a zvýraznění záložky.
> 3. Na scrollování do strany se podívám zítra :)

Ahoj, primárně na tablety necílíme, ale snažil bych se aby to bylo co nejvíc flexibilní. Podlě mě by stačilo fixnout tu velikost obrázku, aby se neroztahoval + zarovnání symbolu "+" doprava a je to úplně v pohodě. Klikání je parádní!

Tak ještě scrollování a můžeme mergovat 😄

2021-07-06 13:58 UTC, Terra42 commented
Ahoj, přidala jsem scrollování.

2021-07-08 08:27 UTC, jirizikes submitted a review, later dismissed

2021-07-08 08:31 UTC, jirizikes requested changes
@Terra42 Ahoj, vypadá to suprově. Jen poslední maličkost, PR by měl být podle pravidel zde: https://github.com/cesko-digital/audiozpravy -> tzn. je potřeba udělat interactive rebase na master a sloučit všechny commity do jednoho. Díky moc!

2021-07-11 15:08 UTC, jirizikes requested changes
Ahoj,
ještě tam máš dva commity :) Zřejmě bude potřeba ještě jednou rebasnout.
Díky, Jirka

2021-07-11 15:08 UTC, jirizikes commented on package-lock.json
> +{
Používáme defaultně yarn, takže tento file by tam neměl vůbec jít.

2021-07-11 15:43 UTC, closed without merging