DT-8 Add player component
cesko-digital/audiozpravy pull request #29
Opened 2021-07-06 22:14 UTC by danielTipelt

![Screenshot 2021-07-07 at 0 07 46](https://user-images.githubusercontent.com/61743743/124672942-39ccbd80-deb8-11eb-99ad-68966b7e422f.png)

2021-07-08 07:13 UTC, jirizikes requested changes
Ahoj,

vypadá to suprově! Díky moc. Mám k tomu dvě věci:

- Co použít jako tu ikonu `10s zpět` přímo to SVG z Figmy? Ať to sedí přesně...
- To je jen maličkost - na tom news feedu bych ten player dal defaultně zavřený (nebo ho třeba zatím dát na jinou page), budeme teď mergovat ten news feed, tak by to tam dělalo bordel..

2021-07-09 06:29 UTC, danielTipelt commented
> * Co použít jako tu ikonu `10s zpět` přímo to SVG z Figmy? Ať to sedí přesně...

✅ 
> * To je jen maličkost - na tom news feedu bych ten player dal defaultně zavřený (nebo ho třeba zatím dát na jinou page), budeme teď mergovat ten news feed, tak by to tam dělalo bordel..

Jasan, ja to tam strcil spis pro to aby bylo videt pouziti obou verzi. Je to pryc.

2021-07-09 06:41 UTC, danielTipelt commented on app/components/typography/description.tsx
> +    {...rest}
Tady se mi nepropisovala definice toho omezeni description na dva radky. Omlouvam se screenshot kde to fungovalo, nevim co bylo spatne 🙈

2021-07-10 11:46 UTC, jirizikes approved these changes
Super díky moc!

2021-07-10 11:46 UTC, merged