Feature/job runner
cesko-digital/audiozpravy pull request #61
Opened 2021-12-19 20:43 UTC by mk-michal

2022-01-06 16:08 UTC, jakubbares requested changes

2022-01-13 20:48 UTC, mk-michal commented on backend/job_runner.py
> +        """ Training doc2vec model based on all articles"""
zavrel nejspis omylem. Tato verze je bez toho, v dalsi si budu hrat s tema predikcema.

2022-01-13 21:03 UTC, mk-michal commented on backend/classes/__init__.py
> -    ZDRAVI = "zdravi"
Nevim co myslis. Hodis mi nejaky priklad?

2022-01-13 21:03 UTC, mk-michal commented on backend/classes/helper.py
> +        'Životní styl a společnost': CategoryEnum.ZIVOTNI_STYL.value,
das mi priklad? nevim co myslis.

2022-01-13 21:05 UTC, jakubbares commented
Koukni do posledni vetve. Je tam psuhnuta classa category
On 13. 1. 2022 22:03 +0100, mk-michal ***@***.***>, wrote:
> @mk-michal commented on this pull request.
> In backend/classes/helper.py:
> > @@ -37,3 +40,28 @@ def format_articles(selected_articles: pd.DataFrame) -> pd.DataFrame:
>
>     )
>
>
>
>     return selected_articles
>
> +
>
> +def category_mapper(keyword):
>
> +    keyword_to_category = {
>
> +        'Zprávy z domova': CategoryEnum.DOMOV.value,
>
> +        'Česko': CategoryEnum.DOMOV.value,
>
> +        'Svět': CategoryEnum.ZAHRANICI,
>
> +        'Zprávy ze světa': CategoryEnum.ZAHRANICI.value,
>
> +        'Sport': CategoryEnum.SPORT.value,
>
> +        'Kultura': CategoryEnum.KULTURA.value,
>
> +        'Zdraví': CategoryEnum.ZDRAVI.value,
>
> +        'Zajímavosti': CategoryEnum.ZAJIMAVOSTI.value,
>
> +        'Ekonomika': CategoryEnum.EKONOMIKA.value,
>
> +        'Životní styl a společnost': CategoryEnum.ZIVOTNI_STYL.value,
>
> das mi priklad? nevim co myslis.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you commented.Message ID: ***@***.***>

2022-01-13 21:05 UTC, mk-michal commented on backend/job_runner.py
> +        "feeds": [
protoze ty ostatni source veci nepotrebujeme ne? Nebo ano? Mel jsem za to ze budeme davat do feedu jenom ctidoma. Kdyztak me oprav a hodim tam i zbytek.

2022-01-16 18:51 UTC, mk-michal commented on backend/job_runner.py
> +        "feeds": [
@jakubbares ping. Jeste prosim resolvni tohle, at muzeme merge

2022-01-26 15:18 UTC, jakubbares approved these changes

2022-01-26 15:18 UTC, merged